version: '3.4'

services:
  tachideskautodl:
    image: ghcr.io/robonau/tachideskautodl:latest
    environment:
      - URLbase=DATABASE_URL
      - username=username # optional for basic auth
      - password=password # optional for basic auth
      - DATABASE_URL=mysql://databaseuser:databasepass@192.168.1.100:3306/database # optional, it just wont try find errors
      - webhookURL=https://discord.com/api/webhooks/foo/bar # optional send errors to a discord webhook
    restart: unless-stopped
    read_only: true