version: '3.4'

services:
  tachideskautodl:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
    environment:
      - URLbase
      - username
      - password
      - DATABASE_URL
      - webhookURL
    volumes:
      - ./:/usr/src/app
    command: ["npm","run", "dev"]
 