version: '3.4'

services:
  tachideskautodl:
    image: tachideskautodl
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
    volumes:
      - ./:/usr/src/app
    command: ["npm", "start"]
 